spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:0000
  cloud:
    config:
      uri: http://localhost:0000
      username: { username }
      password: { password }